substitutions:
  _REGION: "asia-northeast3"
  _REPO: "emory-repo"
  _SERVICE: "emory-server"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Gradle 빌드
  - name: 'gcr.io/cloud-builders/gradle'
    entrypoint: bash
    args:
      - -c
      - |
        chmod +x gradlew
        sed -i 's/\r$//' gradlew || true
        perl -0777 -pe 's/^\xEF\xBB\xBF//' -i gradlew || true
        sh ./gradlew clean build -x test
    id: 'Gradle Build'

  # 2) Docker 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build','-t',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA',
        '.'
      ]
    id: 'Docker Build'

  # 3) Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
      ]
    id: 'Push Image'

  # 4) Cloud Run 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','${_SERVICE}',
        '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA',
        '--region','${_REGION}',
        '--platform','managed',
        '--no-traffic',
        '--port','8080'
      ]
    id: 'Deploy to Cloud Run'


images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'
