spring.application.name=emoryserver

# JWT ??
jwt.secret=${JWT_SECRET:ZGV2LXNlY3JldC0zMi1ieXRlcy0xMjM0NTY3ODkwLWFiY2QtZWY=}
jwt.expiration=${JWT_EXPIRATION:3600000}

# MongoDB ??
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/emory}

# Swagger ??
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true

# Swagger ?? URL? ??? ?? (http ? https ????)
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.override-with-generic-response=false
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
springdoc.servers[0].url=https://emory-server-406346608321.asia-northeast3.run.app

springdoc.swagger-ui.disable-swagger-default-servers=true

# Cloud Run ??? ?? ??
server.forward-headers-strategy=framework
server.use-forward-headers=true

