spring.application.name=emoryserver


# JWT ??
jwt.secret=${JWT_SECRET:ZGV2LXNlY3JldC0zMi1ieXRlcy0xMjM0NTY3ODkwLWFiY2QtZWY=}
jwt.expiration=${JWT_EXPIRATION:3600000}

# MongoDB ??
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/emory}

# ?? ??? OAuth ??
google.calendar.client-id=41518879301-0avuu9usuisurn6qbt9dcjogvps6v6j3.apps.googleusercontent.com
google.calendar.client-secret=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
google.calendar.redirect-uri=http://localhost:8080/api/calendar/oauth2/callback
google.calendar.scope=https://www.googleapis.com/auth/calendar
google.calendar.application-name=Emory Diary App
spring.jackson.time-zone=Asia/Seoul

# Swagger ??
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true

# Swagger ?? URL? ??? ?? (http ? https ????)
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.override-with-generic-response=false
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

springdoc.swagger-ui.disable-swagger-default-servers=true

# Cloud Run ??? ?? ??
server.forward-headers-strategy=framework
server.port=${PORT:8080}

springdoc.use-forwarded-headers=true


logging.level.org.springframework.security=DEBUG
