spring.application.name=emoryserver

# JWT ??
jwt.secret=${JWT_SECRET:ZGV2LXNlY3JldC0zMi1ieXRlcy0xMjM0NTY3ODkwLWFiY2QtZWY=}
jwt.expiration=${JWT_EXPIRATION:3600000}

# MongoDB ??
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/emory}

# Swagger ??
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true

# Swagger ?? URL? ??? ?? (http ? https ????)
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.override-with-generic-response=false
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

springdoc.swagger-ui.disable-swagger-default-servers=true

# Cloud Run ??? ?? ??
server.forward-headers-strategy=framework
server.port=${PORT:8080}
server.address=0.0.0.0

springdoc.use-forwarded-headers=true


logging.level.org.springframework.security=DEBUG
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never

